language: cpp
sudo: true
os: linux
dist: xenial
git:
  depth: 1
matrix:
  include:

  - env: COMPILER=g++-8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        
  - env: COMPILER=clang++-7
      addons: *clang70

script:
- wget -P $TRAVIS_BUILD_DIR/.. https://raw.githubusercontent.com/catchorg/Catch2/v2.0.1/single_include/catch.hpp
- cd $TRAVIS_BUILD_DIR/test
- make -f ./makefile.ubuntu test CXX=$COMPILER
- make -f ./makefile.ubuntu clean
- cd $TRAVIS_BUILD_DIR/example/diff
- make -f ./makefile.ubuntu CXX=$COMPILER
- make -f ./makefile.ubuntu clean
