language: cpp
sudo: true
os: linux
dist: xenial
git:
  depth: 1
matrix:
  include:
  - env: COMPILER=g++-8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - doxygen
  - env: COMPILER=clang++-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-7
        packages:
        - g++-8
        - clang-7
        - doxygen
script:
- wget -P $TRAVIS_BUILD_DIR/.. https://github.com/catchorg/Catch2/releases/download/v2.7.1/catch.hpp
- cd $TRAVIS_BUILD_DIR/test
- make -f ./makefile.ubuntu test CXX=$COMPILER
- make -f ./makefile.ubuntu clean
- cd $TRAVIS_BUILD_DIR/example/diff
- make -f ./makefile.ubuntu CXX=$COMPILER
- make -f ./makefile.ubuntu clean
- doxygen Doxyfile
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
