os: Visual Studio 2017

platform: x64

configuration: Release

clone_depth: 1

install:
  - ps: Invoke-WebRequest -Uri https://raw.githubusercontent.com/catchorg/Catch2/v2.0.1/single_include/catch.hpp -OutFile $env:OSGEO4W_ROOT\include\catch.hpp
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%/example/diff
  - nmake /f makefile.windows

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%/test
  - nmake /f makefile.windows test
